# 1. Use AWS official Python image
FROM public.ecr.aws/lambda/python:3.10

# 2. Copy requirements and install
COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt

# 3. Copy your code
COPY . ${LAMBDA_TASK_ROOT}

# 4. Set the startup command to your handler
CMD [ "main.handler" ]